title: Grav
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
menu:
    - text: Bio
      url: /bio
    - text: Illustrations
      url: /illustrations
    - text: Contact
      url: /#footer
